name: update

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: List files in current directory
        run: ls -al
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Check for data.json
        run: |
          if [ ! -f data.json ]; then 
            echo '{}' > data.json 
          fi   
      - name: Create credentials.json from secret
        run: printf "%s" "${{ secrets.CREDENTIALS }}" > credentials.json
      - name: Check credentials.json existence and permissions
        run: |
          if [ -f credentials.json ]; then
            echo "credentials.json exists"
            ls -l credentials.json
            head -n 5 credentials.json  # Only prints first 5 lines for safety
          else
            echo "credentials.json does not exist"
            exit 1
          fi
      - name: Install all necessary packages
        run: pip install lxml pandas requests beautifulsoup4 html5lib gspread
      - name: Scraping today's data
        run: python "main.py"
      - name: Commit and push any changes
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git pull --rebase origin main
          git push
