name: update

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: List files in current directory
        run: ls -al
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          - name: Install dependencies
          working-directory: ${{ github.workspace }}
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install all necessary packages
        run: pip install jupyter lxml pandas requests beautifulsoup4 html5lib
      - name: Scraping today's data
        run: python "main.py"
      - name: Commit and push any changes
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git pull --rebase origin main
          git push
